{% set name = "pylint-plugin-utils" %}
{% set version = "0.8.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pylint_plugin_utils-{{ version }}.tar.gz
  sha256: d3cebf68a38ba3fba23a873809155562571386d4c1b03e5b4c4cc26c3eee93e4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - python >={{ python_min }},<4.0
    - pylint >=1.7

test:
  imports:
    - pylint_plugin_utils
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/landscapeio/pylint-plugin-utils
  summary: Utilities and helpers for writing Pylint plugins
  license: GPL-2.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - jakirkham
